# src/ui/charts.py

import pandas as pd
import plotly.express as px
import streamlit as st

def render_gamma_clustering_chart(insight):
    if insight.get("gamma_clusters"):
        st.caption("📈 Supporting Chart (computed from yFinance data — not generated by GPT)")
        gamma_df = pd.DataFrame(insight["gamma_clusters"])

        fig = px.scatter(
            gamma_df,
            x="strike",
            y=gamma_df["call_oi"] + gamma_df["put_oi"],
            size=[20 if risk else 10 for risk in gamma_df["pinning_risk"]],
            color=["Pinning Risk" if risk else "Low Risk" for risk in gamma_df["pinning_risk"]],
            title="Gamma Strike Clustering",
            labels={"y": "Total Open Interest"}
        )

        fig.update_layout(
            xaxis_title="Strike Price",
            yaxis_title="Total Open Interest",
            height=500,
            margin=dict(l=50, r=50, t=50, b=50),
            legend_title="Gamma Pinning Risk"
        )

        st.plotly_chart(fig, use_container_width=True)

def render_unusual_flow_chart(insight):
    if insight.get("unusual_flow"):
        st.caption("📈 Supporting Chart (computed from yFinance data — not generated by GPT)")
        unusual_df = pd.DataFrame(insight["unusual_flow"])

        fig = px.bar(
            unusual_df,
            x="strike",
            y="volume",
            color="sentiment",
            color_discrete_map={"bullish": "green", "bearish": "red"},
            title="Unusual Options Flow by Strike",
            labels={"strike": "Strike Price", "volume": "Volume"}
        )

        fig.update_traces(textposition='auto')
        fig.update_layout(
            height=500,
            xaxis_title="Strike Price",
            yaxis_title="Option Volume",
            legend_title="Sentiment",
            barmode="group",
            margin=dict(l=50, r=50, t=50, b=50)
        )

        st.plotly_chart(fig, use_container_width=True)

def render_volatility_premium_chart(insight):
    if all([
        insight.get("realized_vol_90d") is not None,
        insight.get("atm_implied_vol") is not None
    ]):
        st.caption("📈 Supporting Chart (computed from yFinance data — not generated by GPT)")
        vol_df = pd.DataFrame({
            "Metric": ["Realized Vol (90D)", "ATM Implied Vol"],
            "Volatility": [insight["realized_vol_90d"], insight["atm_implied_vol"]]
        })

        fig = px.bar(
            vol_df,
            x="Metric",
            y="Volatility",
            color="Metric",
            text="Volatility",
            title="Realized vs Implied Volatility",
            color_discrete_map={"Realized Vol (90D)": "blue", "ATM Implied Vol": "orange"}
        )

        fig.update_traces(texttemplate='%{text:.2f}%', textposition='auto')
        fig.update_layout(
            yaxis_title="Volatility (%)",
            xaxis_title=None,
            showlegend=False,
            height=400,
            margin=dict(l=50, r=50, t=50, b=50)
        )

        st.plotly_chart(fig, use_container_width=True)

def render_trend_confirmation_chart(insight):
    if all([
        insight.get("ema_20"),
        insight.get("ema_50"),
        insight.get("ema_200")
    ]):
        st.caption("📈 Supporting Chart (computed from yFinance data — not generated by GPT)")
        trend_df = pd.DataFrame({
            "EMA": ["EMA 20", "EMA 50", "EMA 200"],
            "Price": [insight["ema_20"], insight["ema_50"], insight["ema_200"]]
        })

        fig = px.line(
            trend_df,
            x="EMA",
            y="Price",
            markers=True,
            title="Exponential Moving Averages Snapshot"
        )

        fig.update_layout(
            yaxis_title="Price Level",
            xaxis_title=None,
            showlegend=False,
            height=400,
            margin=dict(l=50, r=50, t=50, b=50)
        )

        st.plotly_chart(fig, use_container_width=True)

def render_beta_risk_profile_chart(insight):
    if all([
        insight.get("beta_90d"),
        insight.get("realized_vol_20d"),
        insight.get("implied_vol"),
        insight.get("composite_risk_score")
    ]):
        st.caption("📈 Supporting Chart (computed from yFinance data — not generated by GPT)")
        risk_df = pd.DataFrame({
            "Metric": ["Beta (90D)", "Realized Vol (20D)", "Implied Vol", "Risk Score"],
            "Value": [
                insight["beta_90d"],
                insight["realized_vol_20d"],
                insight["implied_vol"],
                insight["composite_risk_score"] * 10  # scaling to fit chart
            ]
        })

        fig = px.bar(
            risk_df,
            x="Metric",
            y="Value",
            color="Metric",
            text="Value",
            title="Beta-Adjusted Risk Components"
        )

        fig.update_traces(texttemplate='%{text:.2f}', textposition='auto')
        fig.update_layout(
            yaxis_title="Scaled Value",
            xaxis_title=None,
            showlegend=False,
            height=400,
            margin=dict(l=50, r=50, t=50, b=50)
        )

        st.plotly_chart(fig, use_container_width=True)

def render_sentiment_index_chart(insight):
    if insight.get("score") is not None:
        st.caption("📈 Supporting Chart (computed from yFinance data — not generated by GPT)")
        contrib_df = pd.DataFrame({
            "Component": ["Momentum", "Options Flow", "Vol Skew", "Market Correlation"],
            "Value": [
                insight.get("price_momentum_contribution", 0),
                insight.get("options_flow_contribution", 0),
                insight.get("vol_skew_contribution", 0),
                insight.get("market_correlation_contribution", 0)
            ]
        })

        fig = px.bar(
            contrib_df,
            x="Component",
            y="Value",
            color="Component",
            text="Value",
            title=f"Sentiment Score: {insight['score']} ({insight['interpretation'].capitalize()})"
        )

        fig.update_traces(texttemplate='%{text}', textposition='auto')
        fig.update_layout(
            yaxis_title="Contribution Score",
            xaxis_title=None,
            showlegend=False,
            height=400,
            margin=dict(l=50, r=50, t=50, b=50)
        )

        st.plotly_chart(fig, use_container_width=True)
